import 'package:hive/hive.dart';
import 'package:task_manager/core/constants/app_constants.dart';

/// A task. `extends HiveObject` gives it `.save()` and `.delete()` for
/// free once it's been put in a box — mutate a field, call `.save()`,
/// done. That's the whole persistence API; there's no separate
/// repository translating this into something else.
class Task extends HiveObject {
  String id;
  String title;
  String description;
  bool isCompleted;
  DateTime createdAt;

  Task({
    required this.id,
    required this.title,
    required this.description,
    required this.isCompleted,
    required this.createdAt,
  });
}

/// Manual `TypeAdapter` — hand-written instead of generated by
/// `build_runner`/`hive_generator` so the project builds with a plain
/// `flutter pub get`. The field numbers (0..4) must stay stable across
/// app versions; only ever append new fields, never renumber.
class TaskAdapter extends TypeAdapter<Task> {
  @override
  final int typeId = AppConstants.taskTypeId;

  @override
  Task read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Task(
      id: fields[0] as String,
      title: fields[1] as String,
      description: fields[2] as String,
      isCompleted: fields[3] as bool,
      createdAt: fields[4] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, Task obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.description)
      ..writeByte(3)
      ..write(obj.isCompleted)
      ..writeByte(4)
      ..write(obj.createdAt);
  }
}
